/**
 * Auth Fixture — reusable login helpers & authenticated page objects
 *
 * Provides two pre-authenticated contexts:
 *   • memberPage  — logged in as demo_member (MEMBER role)
 *   • adminPage   — logged in as admin (ADMIN role)
 */
import { test as base, Page, expect } from '@playwright/test';
import path from 'path';

// Paths to stored auth states (generated by global.setup.ts)
export const MEMBER_STATE = path.resolve(__dirname, '../.auth/member.json');
export const ADMIN_STATE = path.resolve(__dirname, '../.auth/admin.json');

// ── Test credentials (match seed data) ──────────────────────────────────────
export const TEST_USERS = {
  member: {
    username: 'demo_member',
    password: 'member123',
  },
  admin: {
    username: 'admin',
    password: 'admin123',
  },
} as const;

// ── Reusable login helper ───────────────────────────────────────────────────
export async function loginAs(
  page: Page,
  credentials: { username: string; password: string },
) {
  await page.goto('/login');
  await page.getByLabel('Username').fill(credentials.username);
  await page.getByLabel('Password').fill(credentials.password);
  await page.getByRole('button', { name: 'Login' }).click();
}

// ── Extended test fixture ───────────────────────────────────────────────────
type AuthFixtures = {
  memberPage: Page;
  adminPage: Page;
};

export const test = base.extend<AuthFixtures>({
  memberPage: async ({ browser }, use) => {
    const context = await browser.newContext({
      storageState: MEMBER_STATE,
    });
    const page = await context.newPage();
    await use(page);
    await context.close();
  },

  adminPage: async ({ browser }, use) => {
    const context = await browser.newContext({
      storageState: ADMIN_STATE,
    });
    const page = await context.newPage();
    await use(page);
    await context.close();
  },
});

export { expect };
